import "../globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import { notFound } from "next/navigation";
import { unstable_setRequestLocale } from "next-intl/server";
import "simplebar-react/dist/simplebar.min.css";
import React from "react";
import { Toaster } from "react-hot-toast";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { cn } from "@/lib/utils";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { NextIntlClientProvider } from "next-intl";
import { locales } from "@/lib/navigation";

const inter = Inter({ subsets: ["latin"] });

export function generateStaticParams() {
	return locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
	title: "Prakat",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	if (!locales.includes(locale as any)) notFound();
	const messages = (await import(`../../../messages/${locale}.json`)).default;

	unstable_setRequestLocale(locale);
	return (
		<html lang="en" className="light">
			<Providers>
				<body
					className={cn("min-h-screen font-sans antialiased grainy", inter.className)}
				>
					<NextIntlClientProvider messages={messages}>
						<Toaster />
						<Navbar />
						{children}
						<ReactQueryDevtools initialIsOpen={false} />
					</NextIntlClientProvider>
				</body>
			</Providers>
		</html>
	);
}
